package UI;

import Db.DbFunction;
import Db.Exception.DbConnectException;
import Db.Tables.Persons;

import javax.swing.*;
import java.sql.SQLException;

/**
 *
 * @author pc
 */
public class EditPage extends javax.swing.JFrame {
    private Persons loggedInUser;
    private DbFunction dbFunction;

    /**
     * Creates new form EditPage
     */
    public EditPage() {
        initComponents();
    }
    public EditPage(Persons loggedInUser){
        this.loggedInUser = loggedInUser;
        this.dbFunction = new DbFunction();
        initComponents();
        txtf_edit_page_name.setText(loggedInUser.getName());
        txtf_edit_page_e_mail.setText(loggedInUser.getE_mail());
        txtf_edit_page_person_type.setText(String.valueOf(loggedInUser.getPerson_type()));
        txtf_edit_page_created_at.setText(loggedInUser.getCreated_at().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_edit_page_e_mail = new javax.swing.JLabel();
        lbl_edit_page_name = new javax.swing.JLabel();
        lbl_edit_page_password = new javax.swing.JLabel();
        lbl_edit_page_person_type = new javax.swing.JLabel();
        lbl_edit_page_created_at = new javax.swing.JLabel();
        txtf_edit_page_name = new javax.swing.JTextField();
        txtf_edit_page_e_mail = new javax.swing.JTextField();
        txtf_edit_page_person_type = new javax.swing.JTextField();
        txtf_edit_page_created_at = new javax.swing.JTextField();
        pwrdf_edit_page_password = new javax.swing.JPasswordField();
        rbtn_edit_page_show = new javax.swing.JRadioButton();
        btn_edit_page_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_edit_page_e_mail.setText("E-Mail");

        lbl_edit_page_name.setText("Name");

        lbl_edit_page_password.setText("Password");

        lbl_edit_page_person_type.setText("Person Type");

        lbl_edit_page_created_at.setText("Created At");

        rbtn_edit_page_show.setText("Show");
        rbtn_edit_page_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_edit_page_showActionPerformed(evt);
            }
        });

        btn_edit_page_update.setText("Update");
        btn_edit_page_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_page_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_edit_page_person_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_edit_page_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_edit_page_e_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_edit_page_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_edit_page_created_at, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtf_edit_page_name)
                                        .addComponent(txtf_edit_page_e_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(txtf_edit_page_person_type, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(txtf_edit_page_created_at, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                        .addComponent(pwrdf_edit_page_password))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtn_edit_page_show)
                                .addContainerGap(17, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_edit_page_update, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_edit_page_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtf_edit_page_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_edit_page_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtf_edit_page_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_edit_page_password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pwrdf_edit_page_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rbtn_edit_page_show))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_edit_page_person_type, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtf_edit_page_person_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_edit_page_created_at, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtf_edit_page_created_at, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(btn_edit_page_update, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void btn_edit_page_updateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String name = txtf_edit_page_name.getText();
        String e_mail = txtf_edit_page_e_mail.getText();
        String password = String.valueOf(pwrdf_edit_page_password.getPassword());

        loggedInUser.setName(name);
        loggedInUser.setE_mail(e_mail);
        loggedInUser.setPassword(password);

        try {
            if(dbFunction.updatePerson(loggedInUser)){
                JOptionPane.showMessageDialog(this, "Person updated successfully");
                MainPage mainPage = new MainPage(loggedInUser);
                mainPage.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Person could not be updated");
            }
        } catch (DbConnectException e) {
            throw new RuntimeException(e);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }


    }

    private void rbtn_edit_page_showActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if(rbtn_edit_page_show.isSelected()){
            pwrdf_edit_page_password.setEchoChar((char)0);
            }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_edit_page_update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_edit_page_created_at;
    private javax.swing.JLabel lbl_edit_page_e_mail;
    private javax.swing.JLabel lbl_edit_page_name;
    private javax.swing.JLabel lbl_edit_page_password;
    private javax.swing.JLabel lbl_edit_page_person_type;
    private javax.swing.JPasswordField pwrdf_edit_page_password;
    private javax.swing.JRadioButton rbtn_edit_page_show;
    private javax.swing.JTextField txtf_edit_page_created_at;
    private javax.swing.JTextField txtf_edit_page_e_mail;
    private javax.swing.JTextField txtf_edit_page_name;
    private javax.swing.JTextField txtf_edit_page_person_type;
    // End of variables declaration
}
