package UI;

import Db.DbFunction;
import Db.Exception.DbConnectException;
import Db.Tables.Persons;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.sql.SQLException;

/**
 * @author pc
 */
public class LoginPage extends javax.swing.JFrame {
    private DbFunction dbFunction;
    private Persons person;

    /**
     * Creates new form LoginPage
     */
    public LoginPage() {
        initComponents();
        dbFunction = new DbFunction();
        person = new Persons();
        this.setResizable(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_sign_in = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        lbl_e_mail = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txtf_e_mail = new javax.swing.JTextField();
        cbx_show = new javax.swing.JCheckBox();
        pswrdf_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_sign_in.setBackground(new java.awt.Color(255, 102, 102));
        btn_sign_in.setText("Sign In");
        btn_sign_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_inActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(0, 153, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lbl_e_mail.setText("E-mail");

        lbl_password.setText("Password");

        txtf_e_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_e_mailKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_e_mailKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_e_mailKeyTyped(evt);
            }
        });

        cbx_show.setText("Show");
        cbx_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_showActionPerformed(evt);
            }
        });

        pswrdf_password.setText("Password");
        pswrdf_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswrdf_passwordActionPerformed(evt);
            }
        });
        pswrdf_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswrdf_passwordKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswrdf_passwordKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswrdf_passwordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(btn_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(pswrdf_password))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbl_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtf_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(cbx_show)
                                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtf_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbx_show)
                                        .addComponent(pswrdf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_sign_in, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void btn_sign_inActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        SignInPage signInPage = new SignInPage();
        signInPage.setVisible(true);
        this.dispose();

    }


    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        person.setE_mail(txtf_e_mail.getText());
        person.setPassword(pswrdf_password.getText());
        try {
            if (dbFunction.login(person)) {
                JOptionPane.showMessageDialog(null, "Login Successful");
            } else {
                JOptionPane.showMessageDialog(null, "Login Failed.Try Again");
            }
        } catch (SQLException | DbConnectException throwables) {
            throwables.printStackTrace();
        }

    }

    private void cbx_showActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (cbx_show.isSelected()) {
            pswrdf_password.setEchoChar((char) 0);
        } else {
            pswrdf_password.setEchoChar('*');
        }
    }

    private void pswrdf_passwordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrdf_passwordKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrdf_passwordKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrdf_passwordKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_e_mailKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_e_mailKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_e_mailKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_sign_in;
    private javax.swing.JCheckBox cbx_show;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_e_mail;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JPasswordField pswrdf_password;
    private javax.swing.JTextField txtf_e_mail;
    // End of variables declaration
}
