package UI;


import Db.DbFunction;
import Db.Enum.ECategoryType;
import Db.Enum.EPaymentMethods;
import Db.Exception.DbConnectException;
import Db.Tables.Expenses;
import Db.Tables.Persons;

import javax.swing.*;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.SQLException;

public class MainPage extends javax.swing.JFrame {

    private Persons person;
    private DbFunction dbFunction;
    private Expenses expenses;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        person = new Persons();
        dbFunction = new DbFunction();
        expenses = new Expenses();
        txtf_expenses_date.setText(new Date(System.currentTimeMillis()).toString());
        set_payment_methods_combobox();
        set_categories_combobox();

    }

    private void set_payment_methods_combobox() {
        cmbx_expenses_payment_methods.removeAllItems();
        for (EPaymentMethods paymentMethod : EPaymentMethods.values()) {
            cmbx_expenses_payment_methods.addItem(paymentMethod.getDisplayName());
        }
    }

    private void set_categories_combobox() {
        cmbx_expenses_category.removeAllItems();
        try {
            dbFunction.getCategories().forEach(category -> {
                cmbx_expenses_category.addItem(category.getName());
            });
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private int getSelectedCategoryId() {
        String selectedCategory = (String) cmbx_expenses_category.getSelectedItem();
        if (selectedCategory != null) {
            ECategoryType categoryType = ECategoryType.valueOf(selectedCategory);
            return categoryType.getId();
        } else {
            throw new IllegalArgumentException("No category selected");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        btngrp_expenses = new javax.swing.ButtonGroup();
        pnl_all = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tbdp_db = new javax.swing.JTabbedPane();
        pnl_expenses = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_expenses = new javax.swing.JTable();
        lbl_expenses_id = new javax.swing.JLabel();
        lbl_expenses_cost = new javax.swing.JLabel();
        lbl_expenses_amount = new javax.swing.JLabel();
        lbl_expenses_description = new javax.swing.JLabel();
        lbl_expenses_category = new javax.swing.JLabel();
        lbl_expenses_payment_method = new javax.swing.JLabel();
        lbl_expenses_date = new javax.swing.JLabel();
        txtf_expenses_id = new javax.swing.JTextField();
        txtf_expenses_cost = new javax.swing.JTextField();
        txtf_expenses_amount = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txta_expenses_description = new javax.swing.JTextArea();
        txtf_expenses_date = new javax.swing.JTextField();
        cmbx_expenses_category = new javax.swing.JComboBox<>();
        cmbx_expenses_payment_methods = new javax.swing.JComboBox<>();
        btn_expenses_add = new javax.swing.JButton();
        btn_expenses_update = new javax.swing.JButton();
        lbl_expenses_search = new javax.swing.JLabel();
        txtf_expenses_search = new javax.swing.JTextField();
        rbtn_expenses_asc = new javax.swing.JRadioButton();
        rbtn_expenses_desc = new javax.swing.JRadioButton();
        rbtn_expenses_date = new javax.swing.JRadioButton();
        btn_expenses_search = new javax.swing.JButton();
        btn_expenses_delete = new javax.swing.JButton();
        pnl_expenses_detail = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_expenses_detail = new javax.swing.JTable();
        pnl_categories = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_expenses_categories = new javax.swing.JTable();
        pnl_payment_methods = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_payment_methods = new javax.swing.JTable();
        lbl_name = new javax.swing.JLabel();
        lbl_surname = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_file = new javax.swing.JMenu();
        menu_item_export_excel = new javax.swing.JMenuItem();
        menu_item_import_excel = new javax.swing.JMenuItem();
        menu_item_export_xml = new javax.swing.JMenuItem();
        menu_item_import_xml = new javax.swing.JMenuItem();
        menu_edit = new javax.swing.JMenu();
        menu_item_profile = new javax.swing.JMenuItem();
        menu_item_statistic = new javax.swing.JMenuItem();
        menu_categories = new javax.swing.JMenu();
        menu_expenses_detail = new javax.swing.JMenu();
        menu_payment_methods = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbdp_db.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbdp_dbStateChanged(evt);
            }
        });
        tbdp_db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdp_dbMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbdp_dbMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                tbdp_dbMouseExited(evt);
            }
        });

        pnl_expenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_expensesMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_expensesMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_expensesMouseExited(evt);
            }
        });

        tbl_expenses.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {},
                        {},
                        {},
                        {}
                },
                new String[]{

                }
        ));
        tbl_expenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_expensesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_expenses);

        lbl_expenses_id.setText("Id");

        lbl_expenses_cost.setText("Cost");

        lbl_expenses_amount.setText("Amount");

        lbl_expenses_description.setText("Description");

        lbl_expenses_category.setText("Category");

        lbl_expenses_payment_method.setText("Payment Method");

        lbl_expenses_date.setText("Date");

        txta_expenses_description.setColumns(20);
        txta_expenses_description.setRows(5);
        jScrollPane5.setViewportView(txta_expenses_description);

        cmbx_expenses_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        cmbx_expenses_payment_methods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        btn_expenses_add.setBackground(new java.awt.Color(98, 194, 242));
        btn_expenses_add.setText("Add");
        btn_expenses_add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_expenses_addMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_expenses_addMouseExited(evt);
            }
        });
        btn_expenses_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expenses_addActionPerformed(evt);
            }
        });

        btn_expenses_update.setBackground(new java.awt.Color(226, 165, 165));
        btn_expenses_update.setText("Update");
        btn_expenses_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_expenses_updateMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_expenses_updateMouseExited(evt);
            }
        });
        btn_expenses_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expenses_updateActionPerformed(evt);
            }
        });

        lbl_expenses_search.setText("Search");

        btngrp_expenses.add(rbtn_expenses_asc);
        rbtn_expenses_asc.setText("Asc");
        rbtn_expenses_asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_expenses_ascActionPerformed(evt);
            }
        });

        btngrp_expenses.add(rbtn_expenses_desc);
        rbtn_expenses_desc.setText("Desc");
        rbtn_expenses_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_expenses_descActionPerformed(evt);
            }
        });

        btngrp_expenses.add(rbtn_expenses_date);
        rbtn_expenses_date.setText("Date");
        rbtn_expenses_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_expenses_dateActionPerformed(evt);
            }
        });

        btn_expenses_search.setText("Search");
        btn_expenses_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expenses_searchActionPerformed(evt);
            }
        });

        btn_expenses_delete.setBackground(new java.awt.Color(246, 26, 70));
        btn_expenses_delete.setText("Delete");
        btn_expenses_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_expenses_deleteMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_expenses_deleteMouseExited(evt);
            }
        });
        btn_expenses_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_expenses_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_expensesLayout = new javax.swing.GroupLayout(pnl_expenses);
        pnl_expenses.setLayout(pnl_expensesLayout);
        pnl_expensesLayout.setHorizontalGroup(
                pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18))
                                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lbl_expenses_search, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtf_expenses_search, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_expenses_search)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(rbtn_expenses_asc)
                                                .addGap(18, 18, 18)
                                                .addComponent(rbtn_expenses_desc)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(rbtn_expenses_date)
                                                .addGap(40, 40, 40)))
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl_expenses_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_expenses_cost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_expenses_amount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_expenses_description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_expenses_category, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_expenses_payment_method, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbl_expenses_date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtf_expenses_id, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtf_expenses_cost, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtf_expenses_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 25, Short.MAX_VALUE))
                                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(txtf_expenses_date, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                                                        .addComponent(cmbx_expenses_payment_methods, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(cmbx_expenses_category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addContainerGap())))
                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btn_expenses_add, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_expenses_update, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_expenses_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_expensesLayout.setVerticalGroup(
                pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_expenses_search)
                                        .addComponent(txtf_expenses_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rbtn_expenses_asc)
                                        .addComponent(rbtn_expenses_desc)
                                        .addComponent(rbtn_expenses_date)
                                        .addComponent(btn_expenses_search))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_expenses_add, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_expenses_update, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_expenses_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26))
                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_expenses_id)
                                        .addComponent(txtf_expenses_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_expenses_cost)
                                        .addComponent(txtf_expenses_cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_expenses_amount)
                                        .addComponent(txtf_expenses_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(lbl_expenses_description))
                                        .addGroup(pnl_expensesLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_expenses_category)
                                        .addComponent(cmbx_expenses_category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_expenses_payment_method)
                                        .addComponent(cmbx_expenses_payment_methods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(pnl_expensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_expenses_date)
                                        .addComponent(txtf_expenses_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbdp_db.addTab("Expenses", pnl_expenses);

        pnl_expenses_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_expenses_detailMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_expenses_detailMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_expenses_detailMouseExited(evt);
            }
        });

        tbl_expenses_detail.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {},
                        {},
                        {},
                        {}
                },
                new String[]{

                }
        ));
        tbl_expenses_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_expenses_detailMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_expenses_detail);

        javax.swing.GroupLayout pnl_expenses_detailLayout = new javax.swing.GroupLayout(pnl_expenses_detail);
        pnl_expenses_detail.setLayout(pnl_expenses_detailLayout);
        pnl_expenses_detailLayout.setHorizontalGroup(
                pnl_expenses_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_expenses_detailLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 305, Short.MAX_VALUE))
        );
        pnl_expenses_detailLayout.setVerticalGroup(
                pnl_expenses_detailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_expenses_detailLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 183, Short.MAX_VALUE))
        );

        tbdp_db.addTab("Expenses Detail", pnl_expenses_detail);

        pnl_categories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_categoriesMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_categoriesMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_categoriesMouseExited(evt);
            }
        });

        tbl_expenses_categories.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {},
                        {},
                        {},
                        {}
                },
                new String[]{

                }
        ));
        tbl_expenses_categories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_expenses_categoriesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_expenses_categories);

        javax.swing.GroupLayout pnl_categoriesLayout = new javax.swing.GroupLayout(pnl_categories);
        pnl_categories.setLayout(pnl_categoriesLayout);
        pnl_categoriesLayout.setHorizontalGroup(
                pnl_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_categoriesLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 305, Short.MAX_VALUE))
        );
        pnl_categoriesLayout.setVerticalGroup(
                pnl_categoriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_categoriesLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 183, Short.MAX_VALUE))
        );

        tbdp_db.addTab("Categories", pnl_categories);

        pnl_payment_methods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_payment_methodsMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_payment_methodsMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_payment_methodsMouseExited(evt);
            }
        });

        tbl_payment_methods.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {},
                        {},
                        {},
                        {}
                },
                new String[]{

                }
        ));
        tbl_payment_methods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_payment_methodsMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_payment_methods);

        javax.swing.GroupLayout pnl_payment_methodsLayout = new javax.swing.GroupLayout(pnl_payment_methods);
        pnl_payment_methods.setLayout(pnl_payment_methodsLayout);
        pnl_payment_methodsLayout.setHorizontalGroup(
                pnl_payment_methodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_payment_methodsLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 305, Short.MAX_VALUE))
        );
        pnl_payment_methodsLayout.setVerticalGroup(
                pnl_payment_methodsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_payment_methodsLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 183, Short.MAX_VALUE))
        );

        tbdp_db.addTab("Payment Methods", pnl_payment_methods);

        lbl_name.setText("Name");

        lbl_surname.setText("Surname");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tbdp_db, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_name)
                                        .addComponent(lbl_surname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tbdp_db)
                                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_allLayout = new javax.swing.GroupLayout(pnl_all);
        pnl_all.setLayout(pnl_allLayout);
        pnl_allLayout.setHorizontalGroup(
                pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnl_allLayout.setVerticalGroup(
                pnl_allLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menu_file.setText("File");
        menu_file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_fileMouseEntered(evt);
            }
        });

        menu_item_export_excel.setText("Export Excel");
        menu_item_export_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_export_excelActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_export_excel);

        menu_item_import_excel.setText("Import Excel");
        menu_item_import_excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_import_excelActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_import_excel);

        menu_item_export_xml.setText("Export xml");
        menu_item_export_xml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_export_xmlActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_export_xml);

        menu_item_import_xml.setText("Import xml");
        menu_item_import_xml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_import_xmlActionPerformed(evt);
            }
        });
        menu_file.add(menu_item_import_xml);

        jMenuBar1.add(menu_file);

        menu_edit.setText("Edit");
        menu_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_editMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_editMouseEntered(evt);
            }
        });

        menu_item_profile.setText("Profile");
        menu_item_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_item_profileActionPerformed(evt);
            }
        });
        menu_edit.add(menu_item_profile);

        menu_item_statistic.setText("Statistic");
        menu_edit.add(menu_item_statistic);

        jMenuBar1.add(menu_edit);

        menu_categories.setText("Categories");
        menu_categories.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_categoriesMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_categoriesMouseEntered(evt);
            }
        });
        jMenuBar1.add(menu_categories);

        menu_expenses_detail.setText("Expenses Detail");
        menu_expenses_detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_expenses_detailMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_expenses_detailMouseEntered(evt);
            }
        });
        jMenuBar1.add(menu_expenses_detail);

        menu_payment_methods.setText("Payment Methods");
        menu_payment_methods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_payment_methodsMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_payment_methodsMouseEntered(evt);
            }
        });
        jMenuBar1.add(menu_payment_methods);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnl_all, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void menu_item_export_excelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_item_import_excelActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_item_export_xmlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_item_import_xmlActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbdp_dbStateChanged(javax.swing.event.ChangeEvent evt) {
        // TODO add your handling code here:
    }

    private void tbdp_dbMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_expensesMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void tbdp_dbMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void tbdp_dbMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_expensesMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_expensesMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_expenses_detailMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_expenses_detailMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_expenses_detailMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_categoriesMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_categoriesMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_categoriesMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_payment_methodsMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_payment_methodsMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void pnl_payment_methodsMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void tbl_expensesMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void tbl_expenses_detailMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void tbl_expenses_categoriesMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void tbl_payment_methodsMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_payment_methodsMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_expenses_detailMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_categoriesMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_editMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_fileMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_editMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_categoriesMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_expenses_detailMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_payment_methodsMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void menu_item_profileActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_addActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // TODO add your handling code here:
            int person_id = 1; // Sabit veya giriş yapan kullanıcının ID'si
            BigDecimal cost = new BigDecimal(txtf_expenses_cost.getText());
            BigDecimal amount = new BigDecimal(txtf_expenses_amount.getText());
            String description = txta_expenses_description.getText();
            int category_id = getSelectedCategoryId();
            int payment_method_id = cmbx_expenses_payment_methods.getSelectedIndex() + 1;
            Date date = Date.valueOf(txtf_expenses_date.getText());

            // Expenses nesnesini oluştur
            Expenses expenses = new Expenses();
            expenses.setPerson_id(person_id);
            expenses.setCost(cost);
            expenses.setAmount(amount);
            expenses.setDescription(description);
            expenses.setCategory_id(category_id);
            expenses.setPayment_method_id(payment_method_id);
            expenses.setDate(date);

            // Veritabanına ekle
            dbFunction.insertExpense(expenses);
            JOptionPane.showMessageDialog(this, "Expense added successfully!");

        } catch (DbConnectException | SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to add expense: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Invalid input: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btn_expenses_updateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_deleteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_addMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_addMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:

    }

    private void btn_expenses_updateMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_updateMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_deleteMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_deleteMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void btn_expenses_searchActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rbtn_expenses_dateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rbtn_expenses_descActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void rbtn_expenses_ascActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_expenses_add;
    private javax.swing.JButton btn_expenses_delete;
    private javax.swing.JButton btn_expenses_search;
    private javax.swing.JButton btn_expenses_update;
    private javax.swing.ButtonGroup btngrp_expenses;
    private javax.swing.JComboBox<String> cmbx_expenses_category;
    private javax.swing.JComboBox<String> cmbx_expenses_payment_methods;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lbl_expenses_amount;
    private javax.swing.JLabel lbl_expenses_category;
    private javax.swing.JLabel lbl_expenses_cost;
    private javax.swing.JLabel lbl_expenses_date;
    private javax.swing.JLabel lbl_expenses_description;
    private javax.swing.JLabel lbl_expenses_id;
    private javax.swing.JLabel lbl_expenses_payment_method;
    private javax.swing.JLabel lbl_expenses_search;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JMenu menu_categories;
    private javax.swing.JMenu menu_edit;
    private javax.swing.JMenu menu_expenses_detail;
    private javax.swing.JMenu menu_file;
    private javax.swing.JMenuItem menu_item_export_excel;
    private javax.swing.JMenuItem menu_item_export_xml;
    private javax.swing.JMenuItem menu_item_import_excel;
    private javax.swing.JMenuItem menu_item_import_xml;
    private javax.swing.JMenuItem menu_item_profile;
    private javax.swing.JMenuItem menu_item_statistic;
    private javax.swing.JMenu menu_payment_methods;
    private javax.swing.JPanel pnl_all;
    private javax.swing.JPanel pnl_categories;
    private javax.swing.JPanel pnl_expenses;
    private javax.swing.JPanel pnl_expenses_detail;
    private javax.swing.JPanel pnl_payment_methods;
    private javax.swing.JRadioButton rbtn_expenses_asc;
    private javax.swing.JRadioButton rbtn_expenses_date;
    private javax.swing.JRadioButton rbtn_expenses_desc;
    private javax.swing.JTabbedPane tbdp_db;
    private javax.swing.JTable tbl_expenses;
    private javax.swing.JTable tbl_expenses_categories;
    private javax.swing.JTable tbl_expenses_detail;
    private javax.swing.JTable tbl_payment_methods;
    private javax.swing.JTextArea txta_expenses_description;
    private javax.swing.JTextField txtf_expenses_amount;
    private javax.swing.JTextField txtf_expenses_cost;
    private javax.swing.JTextField txtf_expenses_date;
    private javax.swing.JTextField txtf_expenses_id;
    private javax.swing.JTextField txtf_expenses_search;
    // End of variables declaration
}
