
package UI;

import Db.DbFunction;
import Db.Enum.EPersonType;
import Db.Exception.DbConnectException;
import Db.Tables.Persons;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.SQLException;

/**
 * @author pc
 */
public class SignInPage extends javax.swing.JFrame {
    private Persons person;
    private DbFunction dbFunction;
    private LoginPage loginPage;


    /**
     * Creates new form SignInPage
     */
    public SignInPage() {
        initComponents();
        dbFunction = new DbFunction();
        person = new Persons();
        loginPage = new LoginPage();
        this.setLocationRelativeTo(null);    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pnl_frame = new javax.swing.JPanel();
        pnl_lbl = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_surname = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_confirm_password = new javax.swing.JLabel();
        lbl_e_mail = new javax.swing.JLabel();
        pnl_txtf = new javax.swing.JPanel();
        txtf_name = new javax.swing.JTextField();
        txtf_surname = new javax.swing.JTextField();
        pswrd_password = new javax.swing.JPasswordField();
        pswrd_confirm_password = new javax.swing.JPasswordField();
        cbx_show_password = new javax.swing.JCheckBox();
        cbx_show_confirm_password = new javax.swing.JCheckBox();
        txtf_e_mail = new javax.swing.JTextField();
        pnl_btn = new javax.swing.JPanel();
        btn_sign_up = new javax.swing.JButton();
        lbl_have_account = new javax.swing.JLabel();
        lbl_login = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_login_page = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_name.setText("Name");

        lbl_surname.setText("Surname");

        lbl_password.setText("Password");

        lbl_confirm_password.setText("Confirm Password");

        lbl_e_mail.setText("E-Mail");

        javax.swing.GroupLayout pnl_lblLayout = new javax.swing.GroupLayout(pnl_lbl);
        pnl_lbl.setLayout(pnl_lblLayout);
        pnl_lblLayout.setHorizontalGroup(
                pnl_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_surname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_lblLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbl_e_mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        pnl_lblLayout.setVerticalGroup(
                pnl_lblLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_lblLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl_name, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lbl_surname)
                                .addGap(31, 31, 31)
                                .addComponent(lbl_e_mail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_password, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(lbl_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
        );

        txtf_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_nameKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_nameKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_nameKeyTyped(evt);
            }
        });

        txtf_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_surnameActionPerformed(evt);
            }
        });
        txtf_surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_surnameKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_surnameKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_surnameKeyTyped(evt);
            }
        });

        pswrd_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswrd_passwordKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswrd_passwordKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswrd_passwordKeyTyped(evt);
            }
        });

        pswrd_confirm_password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pswrd_confirm_passwordKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswrd_confirm_passwordKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswrd_confirm_passwordKeyTyped(evt);
            }
        });

        cbx_show_password.setText("Show");
        cbx_show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_show_passwordActionPerformed(evt);
            }
        });

        cbx_show_confirm_password.setText("Show");
        cbx_show_confirm_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_show_confirm_passwordActionPerformed(evt);
            }
        });

        txtf_e_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_e_mailActionPerformed(evt);
            }
        });
        txtf_e_mail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtf_e_mailKeyPressed(evt);
            }

            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtf_e_mailKeyReleased(evt);
            }

            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtf_e_mailKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout pnl_txtfLayout = new javax.swing.GroupLayout(pnl_txtf);
        pnl_txtf.setLayout(pnl_txtfLayout);
        pnl_txtfLayout.setHorizontalGroup(
                pnl_txtfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_txtfLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnl_txtfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtf_e_mail, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addGroup(pnl_txtfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(pswrd_confirm_password, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                                .addComponent(txtf_name, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtf_surname, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pswrd_password, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnl_txtfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbx_show_password, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbx_show_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_txtfLayout.setVerticalGroup(
                pnl_txtfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_txtfLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtf_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtf_e_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(pnl_txtfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pswrd_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbx_show_password))
                                .addGap(27, 27, 27)
                                .addGroup(pnl_txtfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pswrd_confirm_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbx_show_confirm_password))
                                .addGap(29, 29, 29))
        );

        btn_sign_up.setBackground(new java.awt.Color(102, 204, 255));
        btn_sign_up.setText("Sign Up");
        btn_sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sign_upActionPerformed(evt);
            }
        });

        lbl_have_account.setText("Already have a account?");

        lbl_login.setForeground(new java.awt.Color(255, 0, 51));
        lbl_login.setText("Login");
        lbl_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_btnLayout = new javax.swing.GroupLayout(pnl_btn);
        pnl_btn.setLayout(pnl_btnLayout);
        pnl_btnLayout.setHorizontalGroup(
                pnl_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_btnLayout.createSequentialGroup()
                                .addGroup(pnl_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnl_btnLayout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(btn_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(pnl_btnLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lbl_have_account)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_login, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        pnl_btnLayout.setVerticalGroup(
                pnl_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_btnLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btn_sign_up)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(pnl_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_have_account)
                                        .addComponent(lbl_login))
                                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout pnl_frameLayout = new javax.swing.GroupLayout(pnl_frame);
        pnl_frame.setLayout(pnl_frameLayout);
        pnl_frameLayout.setHorizontalGroup(
                pnl_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_frameLayout.createSequentialGroup()
                                .addComponent(pnl_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_frameLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnl_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
        );
        pnl_frameLayout.setVerticalGroup(
                pnl_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_frameLayout.createSequentialGroup()
                                .addGroup(pnl_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnl_txtf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnl_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnl_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menu_login_page.setText("Login Page");
        menu_login_page.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_login_pageMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menu_login_pageMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                menu_login_pageMouseExited(evt);
            }
        });
        jMenuBar1.add(menu_login_page);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnl_frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void txtf_surnameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void lbl_loginMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        loginPage.setVisible(true);
        this.dispose();
    }

    private void btn_sign_upActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String name = txtf_name.getText();
        String surname = txtf_surname.getText();
        String e_mail = txtf_e_mail.getText();
        String password = String.valueOf(pswrd_password.getPassword());
        String confirm_password = String.valueOf(pswrd_confirm_password.getPassword());
        String e_mail_regex = "^[a-z0-9]+(?!.*(?:\\+{2,}|\\-{2,}|\\.{2,}))(?:[\\.+\\-]{0,1}[a-z0-9])*@gmail\\.com$";
        if (name.equals("") || surname.equals("") || e_mail.equals("") || password.equals("") || confirm_password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields");
        } else if (!e_mail.matches(e_mail_regex)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid e-mail address:email@example.com");

        } else if (password.equals(confirm_password)) {
            person.setName(name + " " + surname);
            person.setE_mail(e_mail);
            person.setPassword(password);
            person.setPerson_type(EPersonType.MEMBER);
            person.setCreated_at(new java.sql.Timestamp(System.currentTimeMillis()));
            try {
                dbFunction.insertPerson(person);
            } catch (DbConnectException e) {
                throw new RuntimeException(e);
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Passwords do not match");
            System.err.println("Passwords do not match");
        }
    }

    private void txtf_nameKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_nameKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_nameKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_surnameKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_surnameKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_surnameKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrd_passwordKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrd_passwordKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrd_passwordKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrd_confirm_passwordKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrd_confirm_passwordKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void pswrd_confirm_passwordKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void cbx_show_passwordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (cbx_show_password.isSelected()) {
            pswrd_password.setEchoChar((char) 0);

        } else {
            pswrd_password.setEchoChar('*');
        }
    }

    private void cbx_show_confirm_passwordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        if (cbx_show_confirm_password.isSelected()) {
            pswrd_confirm_password.setEchoChar((char) 0);
        } else {
            pswrd_confirm_password.setEchoChar('*');
        }
    }

    private void menu_login_pageMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        loginPage.setVisible(true);
        this.dispose();
    }

    private void menu_login_pageMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        menu_login_page.setOpaque(true);
        menu_login_page.setBackground(Color.GRAY);
    }

    private void menu_login_pageMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        menu_login_page.setOpaque(false);
        menu_login_page.setBackground(new java.awt.Color(240, 240, 240));

    }

    private void txtf_e_mailActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_e_mailKeyPressed(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_e_mailKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    private void txtf_e_mailKeyTyped(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btn_sign_up;
    private javax.swing.JCheckBox cbx_show_confirm_password;
    private javax.swing.JCheckBox cbx_show_password;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_confirm_password;
    private javax.swing.JLabel lbl_e_mail;
    private javax.swing.JLabel lbl_have_account;
    private javax.swing.JLabel lbl_login;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_surname;
    private javax.swing.JMenu menu_login_page;
    private javax.swing.JPanel pnl_btn;
    private javax.swing.JPanel pnl_frame;
    private javax.swing.JPanel pnl_lbl;
    private javax.swing.JPanel pnl_txtf;
    private javax.swing.JPasswordField pswrd_confirm_password;
    private javax.swing.JPasswordField pswrd_password;
    private javax.swing.JTextField txtf_e_mail;
    private javax.swing.JTextField txtf_name;
    private javax.swing.JTextField txtf_surname;
    // End of variables declaration

}
